const libriPerCategoria = {
      "Narrativa": [
        { titolo: "Il cacciatore di aquiloni", prezzo: "€12,99", img: "https://covers.openlibrary.org/b/id/8231856-L.jpg" },
        { titolo: "La solitudine dei numeri primi", prezzo: "€9,99", img: "https://covers.openlibrary.org/b/id/10583133-L.jpg" },
        { titolo: "Storia di una ladra di libri", prezzo: "€14,50", img: "https://covers.openlibrary.org/b/id/11148785-L.jpg" },
        { titolo: "Le otto montagne", prezzo: "€11,90", img: "https://covers.openlibrary.org/b/id/10909258-L.jpg" },
        { titolo: "L'amica geniale", prezzo: "€10,99", img: "https://covers.openlibrary.org/b/id/10545801-L.jpg" },
        { titolo: "Il nome della rosa", prezzo: "€13,90", img: "https://covers.openlibrary.org/b/id/8235414-L.jpg" }
      ],
      "Thriller": [
        { titolo: "La ragazza del treno", prezzo: "€10,00", img: "https://covers.openlibrary.org/b/id/11127259-L.jpg" },
        { titolo: "Uomini che odiano le donne", prezzo: "€11,99", img: "https://covers.openlibrary.org/b/id/10919718-L.jpg" },
        { titolo: "Shutter Island", prezzo: "€9,75", img: "https://covers.openlibrary.org/b/id/8235393-L.jpg" }
      ],
      "Fantascienza": [
        { titolo: "Dune", prezzo: "€14,90", img: "https://covers.openlibrary.org/b/id/10515265-L.jpg" },
        { titolo: "Fondazione", prezzo: "€12,50", img: "https://covers.openlibrary.org/b/id/10913872-L.jpg" },
        { titolo: "Neuromante", prezzo: "€11,00", img: "https://covers.openlibrary.org/b/id/10431558-L.jpg" }
      ],
      "Fantasy": [
        { titolo: "Il signore degli anelli", prezzo: "€16,99", img: "" },
        { titolo: "Harry Potter e la Pietra Filosofale", prezzo: "€8,90", img: "https://covers.openlibrary.org/b/isbn/8869184074-L.jpg" },
        { titolo: "Eragon", prezzo: "€10,50", img: "https://covers.openlibrary.org/b/id/10919783-L.jpg" }
      ],
      "Romanzo Rosa": [
        { "titolo":"Orgoglio e Pregiudizio","prezzo":"€9,90","img":"https://covers.openlibrary.org/b/id/8225235-L.jpg" },
        { "titolo":"Come l'acqua per il cioccolato","prezzo":"€10,50","img":"https://covers.openlibrary.org/b/id/240729-L.jpg" },
        { "titolo":"Sogni e delitti","prezzo":"€11,20","img":"https://covers.openlibrary.org/b/id/10537547-L.jpg" },
        { "titolo":"Le pagine della nostra vita","prezzo":"€12,00","img":"https://covers.openlibrary.org/b/id/8233754-L.jpg" },
        { "titolo":"Anna Karenina","prezzo":"€13,50","img":"https://covers.openlibrary.org/b/id/8233248-L.jpg" },
        { "titolo":"Il giardino segreto","prezzo":"€10,90","img":"https://covers.openlibrary.org/b/id/8232321-L.jpg" },
        { "titolo":"La prima volta che ho visto Parigi","prezzo":"€11,00","img":"https://covers.openlibrary.org/b/id/10536455-L.jpg" },
        { "titolo":"Uno splendido disastro","prezzo":"€9,80","img":"https://covers.openlibrary.org/b/id/10537841-L.jpg" },
        { "titolo":"Il profumo delle foglie di limone","prezzo":"€12,40","img":"https://covers.openlibrary.org/b/id/10537924-L.jpg" },
        { "titolo":"Le coincidenze dell'amore","prezzo":"€10,30","img":"https://covers.openlibrary.org/b/id/8239023-L.jpg" },
        { "titolo":"Ti amerò sempre, cara","prezzo":"€14,00","img":"https://covers.openlibrary.org/b/id/10536791-L.jpg" },
        { "titolo":"La voce invisibile delle cose","prezzo":"€11,50","img":"https://covers.openlibrary.org/b/id/10537879-L.jpg" }
      ],
      "Storico": [
        { "titolo":"I pilastri della terra","prezzo":"€14,50","img":"https://covers.openlibrary.org/b/id/8248510-L.jpg" },
        { "titolo":"Il nome della rosa","prezzo":"€13,90","img":"https://covers.openlibrary.org/b/id/8224562-L.jpg" },
        { "titolo":"Guerra e Pace","prezzo":"€15,00","img":"https://covers.openlibrary.org/b/id/8230692-L.jpg" },
        { "titolo":"La caduta dei giganti","prezzo":"€12,80","img":"https://covers.openlibrary.org/b/id/8242441-L.jpg" },
        { "titolo":"Il falco e la colomba","prezzo":"€11,50","img":"https://covers.openlibrary.org/b/id/8235423-L.jpg" },
        { "titolo":"La colonna infame","prezzo":"€10,70","img":"https://covers.openlibrary.org/b/id/10537986-L.jpg" },
        { "titolo":"Il guerriero dell'alba","prezzo":"€12,50","img":"https://covers.openlibrary.org/b/id/8249332-L.jpg" },
        { "titolo":"La regina senz'ombra","prezzo":"€11,90","img":"https://covers.openlibrary.org/b/id/8236412-L.jpg" },
        { "titolo":"Il medico di corte","prezzo":"€13,20","img":"https://covers.openlibrary.org/b/id/10537563-L.jpg" },
        { "titolo":"Via col vento","prezzo":"€12,40","img":"https://covers.openlibrary.org/b/id/8234025-L.jpg" },
        { "titolo":"La sposa scomparsa","prezzo":"€10,80","img":"https://covers.openlibrary.org/b/id/10538601-L.jpg" },
        { "titolo":"La storia","prezzo":"€14,00","img":"https://covers.openlibrary.org/b/id/8237782-L.jpg" }
      ],
      "Horror": [
        { "titolo":"Dracula","prezzo":"€9,90","img":"https://covers.openlibrary.org/b/id/8232005-L.jpg" },
        { "titolo":"Frankenstein","prezzo":"€8,90","img":"https://covers.openlibrary.org/b/id/8232021-L.jpg" },
        { "titolo":"It","prezzo":"€12,50","img":"https://covers.openlibrary.org/b/id/8115963-L.jpg" },
        { "titolo":"Shining","prezzo":"€11,90","img":"https://covers.openlibrary.org/b/id/8108070-L.jpg" },
        { "titolo":"Rosemary's Baby","prezzo":"€10,50","img":"https://covers.openlibrary.org/b/id/8233031-L.jpg" },
        { "titolo":"La casa delle belle addormentate","prezzo":"€9,70","img":"https://covers.openlibrary.org/b/id/8231553-L.jpg" },
        { "titolo":"L'Esorcista","prezzo":"€11,20","img":"https://covers.openlibrary.org/b/id/8230232-L.jpg" },
        { "titolo":"Pet Sematary","prezzo":"€10,80","img":"https://covers.openlibrary.org/b/id/8232122-L.jpg" },
        { "titolo":"La bambina che amava Tom Gordon","prezzo":"€10,30","img":"https://covers.openlibrary.org/b/id/8233667-L.jpg" },
        { "titolo":"Cattedrale","prezzo":"€9,90","img":"https://covers.openlibrary.org/b/id/8234103-L.jpg" },
        { "titolo":"L'ombra dell'angelo","prezzo":"€11,50","img":"https://covers.openlibrary.org/b/id/8233536-L.jpg" },
        { "titolo":"La casa delle foglie","prezzo":"€12,00","img":"https://covers.openlibrary.org/b/id/8233741-L.jpg" }
      ],
      "Biografie": [
        { "titolo":"Steve Jobs (Isaacson)","prezzo":"€13,90","img":"https://covers.openlibrary.org/b/id/8234183-L.jpg" },
        { "titolo":"Io sono Malala","prezzo":"€11,50","img":"https://covers.openlibrary.org/b/id/8235022-L.jpg" },
        { "titolo":"La mia vita","prezzo":"€10,70","img":"https://covers.openlibrary.org/b/id/8236123-L.jpg" },
        { "titolo":"Il diario di Anne Frank","prezzo":"€9,80","img":"https://covers.openlibrary.org/b/id/8232162-L.jpg" },
        { "titolo":"Long Walk to Freedom","prezzo":"€12,40","img":"https://covers.openlibrary.org/b/id/8233421-L.jpg" },
        { "titolo":"Becoming","prezzo":"€11,90","img":"https://covers.openlibrary.org/b/id/8232564-L.jpg" },
        { "titolo":"Io, Ibrahim","prezzo":"€10,30","img":"https://covers.openlibrary.org/b/id/8231987-L.jpg" },
        { "titolo":"La mia Africa","prezzo":"€11,00","img":"https://covers.openlibrary.org/b/id/8231895-L.jpg" },
        { "titolo":"Educated","prezzo":"€12,20","img":"https://covers.openlibrary.org/b/id/8234756-L.jpg" },
        { "titolo":"La lunga strada verso la libertà","prezzo":"€13,50","img":"https://covers.openlibrary.org/b/id/8230242-L.jpg" },
        { "titolo":"Unbroken","prezzo":"€12,00","img":"https://covers.openlibrary.org/b/id/8234781-L.jpg" },
        { "titolo":"La principessa Diana (Philip Norman)","prezzo":"€10,90","img":"https://covers.openlibrary.org/b/id/8233385-L.jpg" }
      ],
      "Young Adult": [
        { "titolo":"Hunger Games","prezzo":"€11,50","img":"https://covers.openlibrary.org/b/id/8237081-L.jpg" },
        { "titolo":"Divergent","prezzo":"€10,90","img":"https://covers.openlibrary.org/b/id/8237912-L.jpg" },
        { "titolo":"Colpa delle stelle","prezzo":"€9,80","img":"https://covers.openlibrary.org/b/id/8237531-L.jpg" },
        { "titolo":"Maze Runner","prezzo":"€11,00","img":"https://covers.openlibrary.org/b/id/8238002-L.jpg" },
        { "titolo":"Percy Jackson e gli dei dell'Olimpo","prezzo":"€12,40","img":"https://covers.openlibrary.org/b/id/8238140-L.jpg" },
        { "titolo":"Looking for Alaska","prezzo":"€10,20","img":"https://covers.openlibrary.org/b/id/8236504-L.jpg" },
        { "titolo":"Città di Carta","prezzo":"€10,50","img":"https://covers.openlibrary.org/b/id/8236654-L.jpg" },
        { "titolo":"Il ribelle","prezzo":"€11,20","img":"https://covers.openlibrary.org/b/id/8236723-L.jpg" },
        { "titolo":"Shadowhunters - Città di Ossa","prezzo":"€10,90","img":"https://covers.openlibrary.org/b/id/8236912-L.jpg" },
        { "titolo":"Eleanor & Park","prezzo":"€9,70","img":"https://covers.openlibrary.org/b/id/8237012-L.jpg" },
        { "titolo":"Aristotle and Dante Discover the Secrets of the Universe","prezzo":"€12,90","img":"https://covers.openlibrary.org/b/id/8238004-L.jpg" },
        { "titolo":"Every Day","prezzo":"€10,80","img":"https://covers.openlibrary.org/b/id/8238005-L.jpg" }
      ],
      "Classici": [
        { "titolo":"I promessi sposi","prezzo":"€8,50","img":"https://covers.openlibrary.org/b/id/8234003-L.jpg" },
        { "titolo":"Divina Commedia","prezzo":"€7,90","img":"https://covers.openlibrary.org/b/id/8233992-L.jpg" },
        { "titolo":"Odyssey","prezzo":"€10,00","img":"https://covers.openlibrary.org/b/id/8233985-L.jpg" },
        { "titolo":"Iliade","prezzo":"€10,00","img":"https://covers.openlibrary.org/b/id/8233986-L.jpg" },
        { "titolo":"Madame Bovary","prezzo":"€9,80","img":"https://covers.openlibrary.org/b/id/8233994-L.jpg" },
        { "titolo":"Moby Dick","prezzo":"€11,50","img":"https://covers.openlibrary.org/b/id/8233995-L.jpg" },
        { "titolo":"Guerra dei mondi","prezzo":"€9,70","img":"https://covers.openlibrary.org/b/id/8233998-L.jpg" },
        { "titolo":"Il ritratto di Dorian Gray","prezzo":"€10,20","img":"https://covers.openlibrary.org/b/id/8233999-L.jpg" },
        { "titolo":"Anna Karenina (classico)","prezzo":"€11,00","img":"https://covers.openlibrary.org/b/id/8234000-L.jpg" },
        { "titolo":"Cuore","prezzo":"€8,90","img":"https://covers.openlibrary.org/b/id/8234001-L.jpg" },
        { "titolo":"I ragazzi della via Pál","prezzo":"€9,60","img":"https://covers.openlibrary.org/b/id/8234002-L.jpg" },
        { "titolo":"Robinson Crusoe","prezzo":"€10,50","img":"https://covers.openlibrary.org/b/id/8234004-L.jpg" }
      ],
      "Avventura": [
        { "titolo":"L'isola del tesoro","prezzo":"€9,90","img":"https://covers.openlibrary.org/b/id/8235003-L.jpg" },
        { "titolo":"Ventimila leghe sotto i mari","prezzo":"€10,50","img":"https://covers.openlibrary.org/b/id/8235010-L.jpg" },
        { "titolo":"Il richiamo della foresta","prezzo":"€9,80","img":"https://covers.openlibrary.org/b/id/8235020-L.jpg" },
        { "titolo":"Robinson Crusoe","prezzo":"€10,50","img":"https://covers.openlibrary.org/b/id/8235004-L.jpg" },
        { "titolo":"Il giro del mondo in 80 giorni","prezzo":"€10,20","img":"https://covers.openlibrary.org/b/id/8235030-L.jpg" },
        { "titolo":"La freccia nera","prezzo":"€11,00","img":"https://covers.openlibrary.org/b/id/8235040-L.jpg" },
        { "titolo":"I tre moschettieri","prezzo":"€11,50","img":"https://covers.openlibrary.org/b/id/8235050-L.jpg" },
        { "titolo":"Il conte di Montecristo","prezzo":"€12,00","img":"https://covers.openlibrary.org/b/id/8235060-L.jpg" },
        { "titolo":"Sahara","prezzo":"€11,20","img":"https://covers.openlibrary.org/b/id/8235070-L.jpg" },
        { "titolo":"Il richiamo della foresta (ediz. italiano)","prezzo":"€9,80","img":"https://covers.openlibrary.org/b/id/8235021-L.jpg" },
        { "titolo":"Cuore di tenebra","prezzo":"€10,70","img":"https://covers.openlibrary.org/b/id/8235080-L.jpg" },
        { "titolo":"La montagna incantata","prezzo":"€11,90","img":"https://covers.openlibrary.org/b/id/8235090-L.jpg" }
      ],
      "Umoristico": [
        { "titolo":"Il barone rampante","prezzo":"€10,90","img":"https://covers.openlibrary.org/b/id/8236003-L.jpg" },
        { "titolo":"La coscienza di Zeno","prezzo":"€11,50","img":"https://covers.openlibrary.org/b/id/8236010-L.jpg" },
        { "titolo":"Tre uomini in barca","prezzo":"€9,80","img":"https://covers.openlibrary.org/b/id/8236020-L.jpg" },
        { "titolo":"Guida galattica per autostoppisti","prezzo":"€11,30","img":"https://covers.openlibrary.org/b/id/8232230-L.jpg" },
        { "titolo":"Quattro sovrani dal cuor tenero","prezzo":"€10,20","img":"https://covers.openlibrary.org/b/id/8236030-L.jpg" },
        { "titolo":"Il piccolo principe","prezzo":"€8,90","img":"https://covers.openlibrary.org/b/id/8236040-L.jpg" },
        { "titolo":"Il giovane Holden","prezzo":"€9,70","img":"https://covers.openlibrary.org/b/id/8236050-L.jpg" },
        { "titolo":"Le avventure di Pinocchio","prezzo":"€11,00","img":"https://covers.openlibrary.org/b/id/8236060-L.jpg" },
        { "titolo":"Il visconte dimezzato","prezzo":"€10,50","img":"https://covers.openlibrary.org/b/id/8236070-L.jpg" },
        { "titolo":"Mai dire gol","prezzo":"€12,40","img":"https://covers.openlibrary.org/b/id/8236080-L.jpg" },
        { "titolo":"La parmigiana","prezzo":"€9,60","img":"https://covers.openlibrary.org/b/id/8236090-L.jpg" },
        { "titolo":"Eppure cadiamo felici","prezzo":"€11,20","img":"https://covers.openlibrary.org/b/id/8236100-L.jpg" }
      ],
      "Psicologico": [
        { "titolo":"Il giovane Holden","prezzo":"€9,70","img":"https://covers.openlibrary.org/b/id/8236050-L.jpg" },
        { "titolo":"IT","prezzo":"€12,50","img":"https://covers.openlibrary.org/b/id/8115963-L.jpg" },
        { "titolo":"La coscienza di Zeno","prezzo":"€11,50","img":"https://covers.openlibrary.org/b/id/8236010-L.jpg" },
        { "titolo":"Le città invisibili","prezzo":"€10,90","img":"https://covers.openlibrary.org/b/id/8238010-L.jpg" },
        { "titolo":"Il deserto dei Tartari","prezzo":"€11,20","img":"https://covers.openlibrary.org/b/id/8238020-L.jpg" },
        { "titolo":"Zeno Cosini racconta","prezzo":"€10,50","img":"https://covers.openlibrary.org/b/id/8238030-L.jpg" },
        { "titolo":"La campana di vetro","prezzo":"€12,00","img":"https://covers.openlibrary.org/b/id/8238040-L.jpg" },
        { "titolo":"Il buio oltre la siepe","prezzo":"€11,30","img":"https://covers.openlibrary.org/b/id/8238050-L.jpg" },
        { "titolo":"La strada","prezzo":"€10,80","img":"https://covers.openlibrary.org/b/id/8238060-L.jpg" },
        { "titolo":"Norwegian Wood","prezzo":"€10,90","img":"https://covers.openlibrary.org/b/id/8238070-L.jpg" },
        { "titolo":"Morte e vita delle grandi città","prezzo":"€9,60","img":"https://covers.openlibrary.org/b/id/8238080-L.jpg" },
        { "titolo":"La nausea","prezzo":"€10,20","img":"https://covers.openlibrary.org/b/id/8238090-L.jpg" }
      ],
      "Distopico": [
        { "titolo":"1984","prezzo":"€9,90","img":"https://covers.openlibrary.org/b/id/8226191-L.jpg" },
        { "titolo":"Il mondo nuovo","prezzo":"€11,00","img":"https://covers.openlibrary.org/b/id/8091010-L.jpg" },
        { "titolo":"Fahrenheit 451","prezzo":"€10,50","img":"https://covers.openlibrary.org/b/id/8591673-L.jpg" },
        { "titolo":"Il racconto dell'ancella","prezzo":"€12,40","img":"https://covers.openlibrary.org/b/id/8239010-L.jpg" },
        { "titolo":"La svastica sul sole","prezzo":"€10,80","img":"https://covers.openlibrary.org/b/id/8247606-L.jpg" },
        { "titolo":"Guida galattica per autostoppisti","prezzo":"€11,30","img":"https://covers.openlibrary.org/b/id/8232230-L.jpg" },
        { "titolo":"La quinta onda","prezzo":"€11,20","img":"https://covers.openlibrary.org/b/id/8239020-L.jpg" },
        { "titolo":"Matadora","prezzo":"€10,90","img":"https://covers.openlibrary.org/b/id/8239030-L.jpg" },
        { "titolo":"Ready Player One","prezzo":"€12,00","img":"https://covers.openlibrary.org/b/id/8239040-L.jpg" },
        { "titolo":"The Road (La strada)","prezzo":"€11,30","img":"https://covers.openlibrary.org/b/id/8238050-L.jpg" },
        { "titolo":"Il cerchio","prezzo":"€10,70","img":"https://covers.openlibrary.org/b/id/8239050-L.jpg" },
        { "titolo":"Snowpiercer","prezzo":"€12,50","img":"https://covers.openlibrary.org/b/id/8239060-L.jpg" }
      ],
      "Poesia": [
        { "titolo":"Divina Commedia","prezzo":"€7,90","img":"https://covers.openlibrary.org/b/id/8233992-L.jpg" },
        { "titolo":"Foglie di erba","prezzo":"€9,20","img":"https://covers.openlibrary.org/b/id/8239070-L.jpg" },
        { "titolo":"A Silvia","prezzo":"€5,50","img":"https://covers.openlibrary.org/b/id/8239080-L.jpg" },
        { "titolo":"L'infinito","prezzo":"€5,00","img":"https://covers.openlibrary.org/b/id/8239090-L.jpg" },
        { "titolo":"Canto notturno di un pastore errante dell'Asia","prezzo":"€6,00","img":"https://covers.openlibrary.org/b/id/8239100-L.jpg" },
        { "titolo":"Il lanciatore di giavellotto","prezzo":"€8,50","img":"https://covers.openlibrary.org/b/id/8239110-L.jpg" },
        { "titolo":"Odi a un usignolo","prezzo":"€6,90","img":"https://covers.openlibrary.org/b/id/8239120-L.jpg" },
        { "titolo":"Le rime (Petrarca)","prezzo":"€7,30","img":"https://covers.openlibrary.org/b/id/8239130-L.jpg" },
        { "titolo":"Meriggiare pallido e assorto","prezzo":"€8,20","img":"https://covers.openlibrary.org/b/id/8239140-L.jpg" },
        { "titolo":"Alla sera","prezzo":"€6,50","img":"https://covers.openlibrary.org/b/id/8239150-L.jpg" },
        { "titolo":"Amore e Psiche: poema","prezzo":"€9,00","img":"https://covers.openlibrary.org/b/id/8239160-L.jpg" },
        { "titolo":"Il sabato del villaggio","prezzo":"€6,80","img":"https://covers.openlibrary.org/b/id/8239170-L.jpg" }
  ]
    };